# Generated by Django 3.2 on 2022-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeauto', models.CharField(max_length=50)),
                ('releaseyear', models.IntegerField(default=1900)),
                ('color', models.CharField(max_length=50)),
                ('img', models.TextField()),
                ('price', models.IntegerField(default=20000)),
            ],
        ),
    ]
